name: Publish Mod # publishes on Github, CurseForge & Modrinth

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # download source code to runner's filesystem
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🧩 Read values from gradle.properties
      - name: Load Gradle properties
        id: gradle_props
        run: |
          grep '^minecraft_version=' gradle.properties | cut -d'=' -f2 | tr -d '\r' > temp_version.txt
          echo "MINECRAFT_VERSION=$(cat temp_version.txt)" >> $GITHUB_ENV
          grep '^java_version=' gradle.properties | cut -d'=' -f2 | tr -d '\r' > temp_version.txt
          echo "JAVA_VERSION=$(cat temp_version.txt)" >> $GITHUB_ENV
          grep '^mod_version=' gradle.properties | cut -d'=' -f2 | tr -d '\r' > temp_version.txt
          echo "MOD_VERSION=$(cat temp_version.txt)" >> $GITHUB_ENV
          
          echo "RELEASE_NAME=Crystal Infused ${MOD_VERSION} for Minecraft ${MINECRAFT_VERSION}" >> $GITHUB_ENV
          
          # Read changelog file and store as environment variable
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          cat CHANGELOG.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # sets up java with version indicated in gradle.properties
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      # builds mod using gradle
      - name: Build mod
        run: ./gradlew build

      # publish mod to all platforms
      - name: Publish to Modrinth, CurseForge & GitHub
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

          # Use dynamic env values
          version: ${{ env.MOD_VERSION }}
          name: ${{ env.RELEASE_NAME }}
          game-versions: ${{ env.MINECRAFT_VERSION }}
          java: ${{ env.JAVA_VERSION }}
          changelog: ${{ env.CHANGELOG }}
          files: build/libs/*.jar
